source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'SwiftCountryPicker_Example', :exclusive => true do
  pod "SwiftCountryPicker", :path => "../"
end

target 'SwiftCountryPicker_Tests', :exclusive => true do
  pod "SwiftCountryPicker", :path => "../"

  
end
